### ISSUE TITLE
encountered some bugs when loading dataset

### ISSUE THREAD

**Issue by sitaocheng** [RManLuo/reasoning-on-graphs#5]
Hi there,
I am a graduate student interested in your work!
I am trying to run your code. For the planning inference (getting reasoning path), when running gen_rule_path.py line 122 there is some error. details are below:

Save results to:  results/gen_rule_path/RoG-cwq/RoG/test
Using custom data configuration rmanluo--RoG-cwq-a052b4ae8515a88d
Downloading and preparing dataset parquet/rmanluo--RoG-cwq to /home/v-sitaocheng/.cache/huggingface/datasets/rmanluo___parquet/rmanluo--RoG-cwq-a052b4ae8515a88d/0.0.0/7328ef7ee03eaf3f86ae40594d46a1cec86161704e02dd19f232d81eee72ade8...
Traceback (most recent call last):
  File "/reasoning-on-graphs/src/qa_prediction/gen_rule_path.py", line 235, in <module>
    gen_path = gen_prediction(args)
  File "/reasoning-on-graphs/src/qa_prediction/gen_rule_path.py", line 122, in gen_prediction
    dataset = load_dataset(input_file, split=args.split)
  File "/anaconda/envs/LLM-kbqa/lib/python3.8/site-packages/datasets/load.py", line 1679, in load_dataset
    builder_instance.download_and_prepare(
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/builder.py", line 704, in download_and_prepare
    self._download_and_prepare(
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/builder.py", line 793, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/builder.py", line 1271, in _prepare_split
    writer.write_table(table)
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/arrow_writer.py", line 518, in write_table
    self._build_writer(inferred_schema=pa_table.schema)
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/arrow_writer.py", line 352, in _build_writer
    inferred_features = Features.from_arrow_schema(inferred_schema)
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/features/features.py", line 1533, in from_arrow_schema
    return Features.from_dict(metadata["info"]["features"])
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/features/features.py", line 1562, in from_dict
    obj = generate_from_dict(dic)
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/features/features.py", line 1263, in generate_from_dict
    return {key: generate_from_dict(value) for key, value in obj.items()}
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/features/features.py", line 1263, in <dictcomp>
    return {key: generate_from_dict(value) for key, value in obj.items()}
  File "/anaconda/envs/ccc/lib/python3.8/site-packages/datasets/features/features.py", line 1267, in generate_from_dict
    return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"])
KeyError: 'length'

I looked up on internet and found that there might be the problems on the dataset. Should I download it manually or is there anything wrong?

**Comment by RManLuo** [comment]
Thanks for your interest in our work. Please try to upgrade your Python version to 3.10.

**Comment by sitaocheng** [comment]
Thank you for that. It works.

Now i have another question. I have seen when you "retrieve" after "planning", you use a "graph" column which is right in your dataset. I am wondering how did you get this "graph", could you specific the method? 

appreciate it for your time.

**Comment by RManLuo** [comment]
You can find the code for extracting subgraph [here ](https://github.com/RichardHGL/WSDM2021_NSM/tree/main/preprocessing/Freebase)

**Comment by sitaocheng** [comment]
Thank you so much! I know this process and I am trying to adopt it as well ! 

Nice work! and I will continue to run your code!
