### ISSUE TITLE
Where should I put the datasets?

### ISSUE THREAD

**Issue by caizhuoyue77** [RManLuo/reasoning-on-graphs#9]
Hi, I read your paper and it was really amazing. But I have some questions.

我下载了这两个数据库 "RoG-webqsp" and "RoG-cwq" 也下载了RoG模型的权重。

我把数据文件放在了根目录下面一个叫做rmanluo的文件夹里。

但我在运行这个文件的时候还是报错，说找不到数据文件：rog-reasoning.sh

<img width="269" alt="截屏2024-03-11 15 18 07" src="https://github.com/RManLuo/reasoning-on-graphs/assets/149372809/b1476a6c-c46d-414c-a40a-ed372f56b42c">

下面是报错信息：
```sh
(reasoningongraph) user@user-4U-GPU-Server:/data/czy/projects/reasoning-on-graphs$ ./scripts/rog-reasoning.sh
########
rmanluo/RoG-webqsp
########
Traceback (most recent call last):
  File "/data/czy/projects/reasoning-on-graphs/src/qa_prediction/predict_answer.py", line 236, in <module>
    main(args, LLM)
  File "/data/czy/projects/reasoning-on-graphs/src/qa_prediction/predict_answer.py", line 99, in main
    dataset = load_dataset(input_file, split=args.split)
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 2112, in load_dataset
    builder_instance = load_dataset_builder(
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 1798, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 1429, in dataset_module_factory
    ).get_module()
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 861, in get_module
    module_name, default_builder_kwargs = infer_module_for_data_files(
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 516, in infer_module_for_data_files
    raise FileNotFoundError(f"No (supported) data files or dataset script found{path}")
FileNotFoundError: No (supported) data files or dataset script found in rmanluo/RoG-webqsp. 
########
rmanluo/RoG-cwq
########
Traceback (most recent call last):
  File "/data/czy/projects/reasoning-on-graphs/src/qa_prediction/predict_answer.py", line 236, in <module>
    main(args, LLM)
  File "/data/czy/projects/reasoning-on-graphs/src/qa_prediction/predict_answer.py", line 99, in main
    dataset = load_dataset(input_file, split=args.split)
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 2112, in load_dataset
    builder_instance = load_dataset_builder(
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 1798, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 1429, in dataset_module_factory
    ).get_module()
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 861, in get_module
    module_name, default_builder_kwargs = infer_module_for_data_files(
  File "/data/miniconda3/envs/reasoningongraph/lib/python3.10/site-packages/datasets/load.py", line 516, in infer_module_for_data_files
    raise FileNotFoundError(f"No (supported) data files or dataset script found{path}")
FileNotFoundError: No (supported) data files or dataset script found in rmanluo/RoG-cwq. 
```

能告诉我怎么处理嘛？

**Comment by RManLuo** [comment]
Thanks for your interest in our work. Our code will automatically download the model and data from huggingface. If you want to manually download the data and models please refer to the docs of huggingface.

https://huggingface.co/docs/hub/models-downloading
https://huggingface.co/docs/hub/datasets-downloading

**Comment by caizhuoyue77** [comment]
> Thanks for your interest in our work. Our code will automatically download the model and data from huggingface. If you want to manually download the data and models please refer to the docs of huggingface.
> 
> https://huggingface.co/docs/hub/models-downloading https://huggingface.co/docs/hub/datasets-downloading

Thanks but I already downloaded the data and models. I want to know where to put them. Like a relative path in the folder.

**Comment by RManLuo** [comment]
Please make sure you have properly downloaded the datasets following the docs of hugging face. Then you can specify the dataset path and name with `--data_path` and `-d`.  

I think manually downloading files from huggingface could result in a quite messy directory. So you need to set the  `--data_path` and `-d` to some subfolders to make the code read them properly. I have not tested it yet. I still recommend letting huggingface handle the download and the dataloading process.

**Comment by caizhuoyue77** [comment]
> Please make sure you have properly downloaded the datasets following the docs of hugging face. Then you can specify the dataset path and name with `--data_path` and `-d`.
> 
> I think manually downloading files from huggingface could result in a quite messy directory. So you need to set the `--data_path` and `-d` to some subfolders to make the code read them properly. I have not tested it yet. I still recommend letting huggingface handle the download and the dataloading process.

School'server, don't allow VPN. Sad...

**Comment by RManLuo** [comment]
Maybe you can consider of using some [huggingface mirrors](https://hf-mirror.com/)

**Comment by happyrenxiaozhao** [comment]
@caizhuoyue77 你好，请问你解决了你的问题吗？可以和您交流交流吗？
